### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by Doid-Reyewliz** [BobbyESP/Jetispot#18]
I insert all fields correctly but the app says that I'm not a premium user in Spotify but I have an Individual Premium Plan.

**Comment by BobbyESP** [comment]
Known issue. I'm trying to rebuild the app but the core things has changed a lot and it's hard to keep good.

**Comment by wrobm2** [comment]
is there progress with this or any workaround?

**Comment by CompeyDev** [comment]
@BobbyESP any progress yet? Problem still seems to occur.

**Comment by BobbyESP** [comment]
Yeah, and it will stay. The app needs a rework. I think I'm gonna archive the repo because it really needs work

**Comment by CompeyDev** [comment]
> Yeah, and it will stay. The app needs a rework. I think I'm gonna archive the repo because it really needs work

I'd be very much open to at least create a workaround or patch, if you could lmk how to setup the development environment up.

**Comment by CompeyDev** [comment]
Yup, I found the same - currently looking at what could be done.

**Comment by CompeyDev** [comment]
I took at look at the fork, and it looks like a baseless one. There were no commits made by iTaysonLab, it was simply a fork of librespot-java without any changes made, at a old commit.

I switched the dependency to use the latest official librespot-java implementation. Will update if all goes well.

**Comment by BobbyESP** [comment]
The solution is to remake the app from the ground and scratch with the original librespot-java lib

**Comment by BobbyESP** [comment]
> I took at look at the fork, and it looks like a baseless one. There were no commits made by iTaysonLab, it was simply a fork of librespot-java without any changes made, at a old commit.
> 
> I switched the dependency to use the latest official librespot-java implementation. Will update if all goes well.

I see. I tried to update the lib also, but the compiler gives 800000000 errors and it brokes all (missing classes and proto files changed, etc...)

**Comment by CompeyDev** [comment]
> > I took at look at the fork, and it looks like a baseless one. There were no commits made by iTaysonLab, it was simply a fork of librespot-java without any changes made, at a old commit.
> > I switched the dependency to use the latest official librespot-java implementation. Will update if all goes well.
> 
> I see. I tried to update the lib also, but the compiler gives 800000000 errors and it brokes all (missing classes and proto files changed, etc...)

My assumption was incorrect, he did indeed make edits.

https://github.com/iTaysonLab/librespot-java/commits/dev-jsp

**Comment by CompeyDev** [comment]
Oh and, I'm not a professional JVM dev or anything, so I barely have any clue as to what I'm doing haha... just trying to pick things up as we go.

**Comment by CompeyDev** [comment]
> Hahah okay, don't worry, but yeah, this app is kind of special. I can do my own fork and fix this but I'm focused in Spowlo right now

That'd be great if you could that whenever you're free :)

**Comment by CompeyDev** [comment]
Could you at least tell me what the last functional version of Jetispot was?

**Comment by BobbyESP** [comment]
> > Hahah okay, don't worry, but yeah, this app is kind of special. I can do my own fork and fix this but I'm focused in Spowlo right now
> 
> That'd be great if you could that whenever you're free :)

Okayy, will try!

**Comment by BobbyESP** [comment]
> Could you at least tell me what the last functional version of Jetispot was?

The latest published was. Spotify changed its auth flow and all went broken

**Comment by CompeyDev** [comment]
> > Could you at least tell me what the last functional version of Jetispot was?
> 
> The latest published was. Spotify changed its auth flow and all went broken

Ah, I see. Thought it was an issue with a bug in the library or something at some commit.

**Comment by neeeerrd** [comment]
Upstream Jetispot just got a fix by updating librespot-java I believe. Could the same thing be done with this fork to make it work?

**Comment by BobbyESP** [comment]
My build already has it fixed, but I haven't uploaded it, sorry. Maybe I will check later for the build and upload it here, but I'm very busy rn 😩💀

**Comment by CompeyDev** [comment]
That's awesome! Please consider pushing & creating a release ASAP, would be greatly appreciated :)

**Comment by BobbyESP** [comment]
Fixed

**Comment by baraary** [comment]
Sorry but the problem is still there and still can't login. Its either says wrong Usernam or password or 2~3 sec after pressing sign in, app will close itself.

**Comment by fxzxmicah** [comment]
Yes, I have also been prompted for incorrect username or password, but I am sure they are correct.

**Comment by jacksongoode** [comment]
Doesn't work for me currently.
